version: "3.9"

networks:
  # proxy-network:
  #   driver: "bridge"
  server-network:
    driver: "bridge"
  client-network:
    driver: "bridge"

volumes:
  db-data: {}

services:
  db:
    container_name: db-postgres
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: always
    networks:
      - server-network
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: server-nestjs
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - server-network
    depends_on:
      - db
      - web-rtc
      - redis

  web-rtc:
    container_name: livekit
    image: livekit/livekit-server:latest
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    ports:
      - 7880:7880
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    networks:
      - server-network

  redis:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    networks:
      - server-network
    command: redis-server --save 20 1 --loglevel warning --requirepass mypass
    volumes:
      - ./redis/data:/data
