version: "3.9"

networks:
  server-network:
    driver: "bridge"

volumes:
  db-data: {}

services:
  db:
    container_name: db-postgres
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: always
    networks:
      - server-network
    volumes:
      - db-data:/var/lib/postgresql/data
