version: "3.9"
networks:
  proxy-network:
    driver: bridge
  server-network:
    driver: bridge

volumes:
  db-data: {}
  cache-data: {}
  letsencrypt: {}

services:
  reverse-proxy:
    image: traefik:v2.4
    container_name: traefik
    ports:
      - 443:443
      - 80:80
      - 8080:8080
      - 5000:5000
      - 7880:7880
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt:/letsencrypt
    networks:
      - proxy-network
    command:
      - --api.insecure=true
      - --api.dashboard=true
      - --api.debug=true
      - --providers.docker.network=proxy-network
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --log.LEVEL=INFO
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certresolver=myresolver
      - --entryPoints.webapi.address=:5000
      - --entryPoints.webrtcapi.address=:7880
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.myresolver.acme.email=dangnhatminh09032002@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json

  db:
    container_name: db-postgres
    image: postgres:12
    restart: always
    ports:
      - 5433:5432
    networks:
      - server-network
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres

  client:
    container_name: reactjs
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-network
      - traefik.http.routers.client.rule=Host(`localhost`)
      - traefik.http.routers.client.tls=true
      - traefik.http.routers.client.tls.certresolver=myresolver
      - traefik.http.routers.client.entrypoints=websecure
      - traefik.http.services.client.loadbalancer.server.port=3000

  server:
    container_name: server-nestjs
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    networks:
      - proxy-network
      - server-network
    depends_on:
      - db
      - web_rtc
      - cache_store
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-network
      - traefik.http.routers.server.tls=true
      - traefik.http.routers.server.tls.certresolver=myresolver
      - traefik.http.routers.server.rule=Host(`localhost`)
      - traefik.http.routers.server.entrypoints=webapi
      - traefik.http.services.server.loadbalancer.server.port=5000

  web_rtc:
    container_name: livekit
    image: livekit/livekit-server:v1.5
    command: --config /etc/livekit.yaml
    restart: always
    volumes:
      - ./livekit/livekit.yaml:/etc/livekit.yaml
    networks:
      - server-network
      - proxy-network
    depends_on:
      - cache_store
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-network
      - traefik.http.routers.web_rtc.tls=true
      - traefik.http.routers.web_rtc.tls.certresolver=myresolver
      - traefik.http.routers.web_rtc.rule=Host(`localhost`)
      - traefik.http.routers.web_rtc.entrypoints=webrtcapi # attach this router to the entrypoint named sonarqube
      - traefik.http.services.web_rtc.loadbalancer.server.port=7880

  cache_store:
    container_name: redis
    image: redis:7
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass mypass
    volumes:
      - cache-data:/data
    networks:
      - server-network
