version: "3.9"

networks:
  # proxy-network:
  #   driver: "bridge"
  server-network:
    driver: "bridge"
  client-network:
    driver: "bridge"

volumes:
  db-data: {}

services:
  db:
    container_name: db-postgres
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    restart: always
    networks:
      - server-network
    volumes:
      - db-data:/var/lib/postgresql/data

  server:
    container_name: server-nestjs
    environment:
      - NODE_ENV=development
      - DB_HOST=db-postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=postgres
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - server-network
    depends_on:
      - db
