global:
  checkNewVersion: true
  sendAnonymousUsage: true

log:
  level: info

api:
  dashboard: true
  debug: true
  insecure: true

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  cloudflare:
    acme:
      email: "dangnhatminh09032002@gmail.com"
      storage: "/etc/config/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
          permanent: false # if false, redirect use 302 status
  https:
    address: :443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock" # Listen to the UNIX Docker socket
    exposedByDefault: false # Only expose container that are explicitly enabled (using label traefik.enabled)
    network: "proxy-network" # Default network to use for connections to all containers.
    swarmMode: false # Activates the Swarm Mode (instead of standalone Docker).
    swarmModeRefreshSeconds: "15" # Defines the polling interval (in seconds) in Swarm Mode.
    watch: true # Watch Docker Swarm events
  file:
    filename: "/etc/config/dynamic.yml" # Link to the dynamic configuration
    watch: true # Watch for modifications
  providersThrottleDuration: "10" # Configuration reload frequency
